### ISSUE TITLE
Code to plot the Loss Landscape 

### ISSUE THREAD

**Issue by David-Morales-Norato** [Intelligent-Sensing/NeuWS#1]
Dear authors,

Thank you excellent contributions.

![image](https://github.com/Intelligent-Sensing/NeuWS/assets/46037413/d1dde8d7-760f-40be-b1dd-86862c8a8f77)

I am particularly interested in the python code that was used to generate this plot from Figure S4 from the supplementary material, as I want to compare your method with a new method that I am working in a similar manner. Would it be possible for you to share this code with me? 

Thank you for your time and consideration.

Best regards,

David Norato

**Comment by brandonyfeng** [comment]
The 3D plot was actually not generated using Python. Instead, after obtaining the 2D heat map, we use Blender to generate the 3D landscape. Specifically, we apply those 2D intensity values as displacement of vertices on a 2D planar mesh.

This is an example of using Blender to deform a 2D planar mesh into a 3D "landscape": https://youtu.be/EDVXIwWeoD0.
This prior work used an alternative way to generate landscape plots: https://github.com/tomgoldstein/loss-landscape, not using Blender nor Python.
