### ISSUE TITLE
Save model or model test

### ISSUE THREAD

**Issue by Legendsevl** [Intelligent-Sensing/NeuWS#2]
Hi,
    Your work is excellent, and I have successfully implemented the method based on the data you provided. But I have a question，your code does not provide the function of saving the model or verifying the model on other data. I only see the Measurement and I_est images you saved in different epochs, but these results are displayed on the data within the training set. Therefore, are these results caused by overfitting?
![e_923_it_8](https://github.com/Intelligent-Sensing/NeuWS/assets/38028294/b047eb1a-b9d1-4b08-b852-dbf85ce2a639)

**Comment by brandonyfeng** [comment]
@Legendsevl The purpose of network training here is different than typical deep learning. Our goal is not to learn a model that generalize to other new data. Rather, the goal is to decompose the blurry image measurements into two parts (each represented by a neural network): original image + aberration. In some sense, we purposefully "overfit" the current measurements, and ultimately we get a nice separation between the image and aberration. The network is just a proxy to represent this particular image. To handle a new scene, the assumption is to capture a similar set of blurry measurements for this new scene and do a different round of training to obtain the sharp image for that new scene.

**Comment by Legendsevl** [comment]
Okay, thank you for your answer.
